"""add policy_chunks table

Revision ID: 6a2222ba14ef
Revises: e20608c5f822
Create Date: 2026-09-16 13:58:26.035864

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector


# revision identifiers, used by Alembic.
revision: str = '6a2222ba14ef'
down_revision: Union[str, Sequence[str], None] = 'e20608c5f822'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # pgvector's Vector type depends on this extension existing. Never
    # auto-detected by autogenerate -- was created by hand on local
    # Postgres (step 0.8) and Neon (step 1.17), never captured in a
    # migration until now. IF NOT EXISTS makes this safe to run on both
    # existing environments and a genuinely fresh clone.
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    op.create_table('policy_chunks',
    sa.Column('chunk_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('document', sa.String(length=60), nullable=False),
    sa.Column('section', sa.String(length=120), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('embedding', Vector(384), nullable=True),
    sa.CheckConstraint("document IN ('returns_policy', 'shipping_policy', 'refund_policy')", name='ck_policy_chunks_document_valid'),
    sa.PrimaryKeyConstraint('chunk_id')
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('policy_chunks')
    # ### end Alembic commands ###
