"""add pending_returns table

Revision ID: e762b4c88e27
Revises: 6a2222ba14ef
Create Date: 2026-09-19 14:25:12.841097

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e762b4c88e27'
down_revision: Union[str, Sequence[str], None] = '6a2222ba14ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pending_returns',
    sa.Column('pending_return_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.String(length=20), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('confirmation_token', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("status IN ('pending', 'confirmed', 'expired')", name='ck_pending_returns_status_valid'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.customer_id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.order_id'], ),
    sa.PrimaryKeyConstraint('pending_return_id'),
    sa.UniqueConstraint('confirmation_token', name='uq_pending_returns_confirmation_token')
    )
    op.create_index(op.f('ix_pending_returns_customer_id'), 'pending_returns', ['customer_id'], unique=False)
    op.create_index(op.f('ix_pending_returns_order_id'), 'pending_returns', ['order_id'], unique=False)
    op.create_index(op.f('ix_pending_returns_status'), 'pending_returns', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pending_returns_status'), table_name='pending_returns')
    op.drop_index(op.f('ix_pending_returns_order_id'), table_name='pending_returns')
    op.drop_index(op.f('ix_pending_returns_customer_id'), table_name='pending_returns')
    op.drop_table('pending_returns')
    # ### end Alembic commands ###
